apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-web-app
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      containers:
        - name: sa-web-app
          image: ruizhi1997/sentiment-analysis-web-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
